# Generated by Django 6.1 on 2026-09-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=255)),
                ('oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_oferta', models.PositiveIntegerField(blank=True, null=True)),
                ('oferta_restante', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.CharField(default='general', max_length=80)),
            ],
        ),
    ]
